name: SFB Automated UI Tests

on:
  workflow_dispatch:
  schedule:
     #Runs "every midnight" (see https://crontab.guru)
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'  # Replace with your desired .NET version

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build and run tests
      run: dotnet test --logger "trx;LogFileName=test_results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/*.trx'
