name: Selenium Tests on Windows
on:
  workflow_dispatch:
  schedule:
     #Runs "every midnight" (see https://crontab.guru)
    - cron: "0 0 * * *"


jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.5'  # Change to your desired .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run Windows-Selenium tests
        run: dotnet test --filter FullyQualifiedName~YourNamespace.YourTestClass
