name: Selenium Tests on Windows
on:
  workflow_dispatch:
  schedule:
     #Runs "every midnight" (see https://crontab.guru)
    - cron: "0 0 * * *"


jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'  # Change to your desired .NET version

      - name: Restore NuGet packages
        run:  nuget restore SFB_Test_Automation.sln
        
      - name: add dotnet source
        run:  dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org --configfile $env:APPDATA\NuGet\NuGet.Config

      - name: Build
       
        run: dotnet build SFB_Test_Automation.sln --configuration Release --no-restore

      - name: Run Windows-Selenium tests
        run: dotnet test SFB_Test_Automation.sln --no-restore --verbosity normal
        #run: dotnet test --filter FullyQualifiedName~YourNamespace.YourTestClass
